version: '3.8'

volumes:
  db-init:
  db-data:

services:
  db:
    build:
      context: ./
      dockerfile: ./docker_files/mysql/Dockerfile
    container_name: gorm-sample-db
    restart: on-failure:5
    ports:
      - '3306:3306'
    environment:
      # 今回は勉強用のためセキュリティ無視で直書き
      MYSQL_ROOT_PASSWORD: 'root'
    tty: true
    volumes:
      - db-init:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --skip-character-set-client-handshake
    networks:
      - gormsamplenet
  backend:
    build:
      context: ./
      dockerfile: ./docker_files/go/Dockerfile
    container_name: gorm-sample
    volumes:
      - '.:/go/src/app'
    ports:
      - '9002:9002'
    tty: true
    stdin_open: true
    depends_on:
      - db
    networks:
      - gormsamplenet
networks:
  gormsamplenet:
